--- 
- name: set up webserver
  hosts: default
  become: true
  tasks: 
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes
    - copy: 
        src: /home/administrator/packer/ubuntu22.04/index.html
        dest: /var/www/html/