---
- name: set up webserver
  hosts: default
  become: true
  become_method: runas
  become_user: Administrator
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: yes
        include_management_tools: yes
    - name: Copy index text page
      win_copy:
        src: "./index.html"
        dest: "C:\\inetpub\\wwwroot\\index.html"